FROM golang:alpine AS builder
RUN go env -w GO111MODULE=on
RUN go env -w GOPROXY=https://goproxy.cn,direct
RUN mkdir /app
COPY . /app
WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux go build -o apigateway -a -tags netgo -ldflags '-s -w' ./library-apigateway

FROM scratch
LABEL justin justin@
COPY --from=builder /app/apigateway .
COPY --from=builder /app/library-apigateway/apigateway.yaml .
EXPOSE  10087
ENTRYPOINT ["/apigateway"]