FROM golang:alpine AS builder
RUN go env -w GO111MODULE=on
RUN go env -w GOPROXY=https://goproxy.cn,direct
RUN mkdir /app
COPY . /app
WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux go build -o book-service -a -tags netgo -ldflags '-s -w' ./library-book-service

FROM scratch
LABEL justin justin@
COPY --from=builder /app/book-service .
COPY --from=builder /app/library-book-service/book.yaml .
EXPOSE  10087
ENTRYPOINT ["/book-service"]