server:
  port: 10087
  mode: debug
  name: "book-service"

mysql:
  host: "localhost"
  port: 3306
  db: "library"
  username: "root"
  password: "123456"
  debug: true

ratelimit:
  fillInterval: 1
  capacity: 3

consul:
  addr: "http://consul-server:8500"
  interval: 10s
  timeout: 1s

zipkin:
  url: "http://zipkin-server:9411/api/v2/spans"
  service_name: "book-service"
  reporter:
    timeout: 5
    batch_size: 1000
    batch_interval: 3
    max_backlog: 10000
    