global:
  scrape_interval: 15s
  external_labels:
    monitor: 'library-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
     - targets: ['192.168.1.11:9090']
       labels:
        group: 'local'
  
  - job_name: 'library'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.11:10086', '192.168.1.11:10087', '192.168.1.11:10089']
        labels:
          group: 'library'
          
